In [2]:
import pandas as pd
import numpy as np

import json
from pprint import pprint
import matplotlib.pyplot as plt

import seaborn as sb

In [3]:
file = "RatingsLatLongYear.js"
# Open JSON Files
with open(file) as f:
    data = json.load(f)

beerData = pd.DataFrame(data)
beerData.head(25)

,Average ABV,Average Calories,Average IBU,Average Score,Google Rating,Name,Total Ratings,Year Opened,lat,long
0,6.540741,196.222222,30.687500,2.968000,4.6,The Big Rip,74,2013,39.125946,-94.578436
1,7.925000,237.750000,36.950000,3.612000,4.8,Boulevard,16237,1989,39.082248,-94.596602
2,5.731250,171.937500,21.300000,3.082857,4.5,Brewery Emperial,26,2016,39.090638,-94.578785
3,6.146154,184.769231,38.181818,3.050833,4.1,Calibration,19,2016,39.141180,-94.578750
4,6.183333,185.500000,46.461538,3.218500,4.6,Cinder Block,143,2013,39.140252,-94.579157
5,7.003125,210.093750,44.769231,3.066667,4.6,Double Shift,37,2015,39.091599,-94.577906
6,6.077778,182.166667,25.250000,3.174000,4.7,KC Bier,121,2014,38.985109,-94.595573
7,7.985000,239.550000,42.529412,3.269000,4.7,Martin City,145,2010,38.882761,-94.589858
8,6.493333,194.800000,33.642857,3.075714,4.7,Strange Days,21,2018,39.110027,-94.579975
9,7.874359,236.230769,44.812500,3.198611,4.6,Torn Label,145,2014,39.092553,-94.573076
10,5.666667,170.000000,NaN,3.108333,4.5,Casual Animal,24,2018,39.092430,-94.579894
11,5.989474,179.631579,39.611111,3.115556,4.6,Stockyards,40,2015,39.094318,-94.605282
12,5.670000,170.100000,24.538462,3.304103,4.8,Crane,296,2015,39.004638,-94.462348
13,6.100000,183.000000,44.750000,3.091111,4.6,Border Brewing,19,2014,39.091602,-94.577989
14,5.361538,160.846154,NaN,3.120000,4.9,BKS,14,2017,39.013333,-94.725976
15,0.000000,0.000000,0.000000,0.000000,4.3,Green Room,0,2012,39.054571,-94.592997
16,0.000000,0.000000,0.000000,0.000000,4.4,McCoy's,0,1997,39.053362,-94.591739
17,0.000000,0.000000,0.000000,0.000000,4.7,East Forty,0,2018,40.140343,-96.665205
18,0.000000,0.000000,0.000000,0.000000,4.8,Call Sign,0,2018,39.135419,-94.573751
19,0.000000,0.000000,0.000000,0.000000,4.7,Colony,0,2016,39.142119,-94.577046
20,0.000000,0.000000,0.000000,0.000000,4.4,Rock and Run,0,2013,39.246199,-94.419025

In [4]:
beerData.loc[17,'lat'] = 39.0185
beerData.loc[17,'long'] = -94.2782
beerData.head(25)

,Average ABV,Average Calories,Average IBU,Average Score,Google Rating,Name,Total Ratings,Year Opened,lat,long
0,6.540741,196.222222,30.687500,2.968000,4.6,The Big Rip,74,2013,39.125946,-94.578436
1,7.925000,237.750000,36.950000,3.612000,4.8,Boulevard,16237,1989,39.082248,-94.596602
2,5.731250,171.937500,21.300000,3.082857,4.5,Brewery Emperial,26,2016,39.090638,-94.578785
3,6.146154,184.769231,38.181818,3.050833,4.1,Calibration,19,2016,39.141180,-94.578750
4,6.183333,185.500000,46.461538,3.218500,4.6,Cinder Block,143,2013,39.140252,-94.579157
5,7.003125,210.093750,44.769231,3.066667,4.6,Double Shift,37,2015,39.091599,-94.577906
6,6.077778,182.166667,25.250000,3.174000,4.7,KC Bier,121,2014,38.985109,-94.595573
7,7.985000,239.550000,42.529412,3.269000,4.7,Martin City,145,2010,38.882761,-94.589858
8,6.493333,194.800000,33.642857,3.075714,4.7,Strange Days,21,2018,39.110027,-94.579975
9,7.874359,236.230769,44.812500,3.198611,4.6,Torn Label,145,2014,39.092553,-94.573076
10,5.666667,170.000000,NaN,3.108333,4.5,Casual Animal,24,2018,39.092430,-94.579894
11,5.989474,179.631579,39.611111,3.115556,4.6,Stockyards,40,2015,39.094318,-94.605282
12,5.670000,170.100000,24.538462,3.304103,4.8,Crane,296,2015,39.004638,-94.462348
13,6.100000,183.000000,44.750000,3.091111,4.6,Border Brewing,19,2014,39.091602,-94.577989
14,5.361538,160.846154,NaN,3.120000,4.9,BKS,14,2017,39.013333,-94.725976
15,0.000000,0.000000,0.000000,0.000000,4.3,Green Room,0,2012,39.054571,-94.592997
16,0.000000,0.000000,0.000000,0.000000,4.4,McCoy's,0,1997,39.053362,-94.591739
17,0.000000,0.000000,0.000000,0.000000,4.7,East Forty,0,2018,39.018500,-94.278200
18,0.000000,0.000000,0.000000,0.000000,4.8,Call Sign,0,2018,39.135419,-94.573751
19,0.000000,0.000000,0.000000,0.000000,4.7,Colony,0,2016,39.142119,-94.577046
20,0.000000,0.000000,0.000000,0.000000,4.4,Rock and Run,0,2013,39.246199,-94.419025

In [6]:
fringe = pd.DataFrame([{"Average ABV": 0, "Average Calories": 0, "Average IBU": 0, "Average Score": 0,
                 "Google Rating": 4.8, "Name": "Fringe Beerworks", "Total Ratings": 0,
                 "lat":38.9128, "long":-94.3766, "Year Opened": 2016}])

smoke = pd.DataFrame([{"Average ABV": 0, "Average Calories": 0, "Average IBU": 0, "Average Score": 0,
                 "Google Rating": 4.3, "Name": "Smoke Brewing", "Total Ratings": 0,
                 "lat":38.9131, "long":-94.3778, "Year Opened": 2016}])

newaxiom = pd.DataFrame([{"Average ABV": 0, "Average Calories": 0, "Average IBU": 0, "Average Score": 0,
                 "Google Rating": 4.8, "Name": "New Axiom", "Total Ratings": 0,
                 "lat":38.9207, "long":-94.3588, "Year Opened": 2018}])

beerData = beerData.append(fringe)
beerData = beerData.append(smoke)
beerData = beerData.append(newaxiom)


beerData.head(25)

,Average ABV,Average Calories,Average IBU,Average Score,Google Rating,Name,Total Ratings,Year Opened,lat,long
0,6.540741,196.222222,30.687500,2.968000,4.6,The Big Rip,74,2013,39.125946,-94.578436
1,7.925000,237.750000,36.950000,3.612000,4.8,Boulevard,16237,1989,39.082248,-94.596602
2,5.731250,171.937500,21.300000,3.082857,4.5,Brewery Emperial,26,2016,39.090638,-94.578785
3,6.146154,184.769231,38.181818,3.050833,4.1,Calibration,19,2016,39.141180,-94.578750
4,6.183333,185.500000,46.461538,3.218500,4.6,Cinder Block,143,2013,39.140252,-94.579157
5,7.003125,210.093750,44.769231,3.066667,4.6,Double Shift,37,2015,39.091599,-94.577906
6,6.077778,182.166667,25.250000,3.174000,4.7,KC Bier,121,2014,38.985109,-94.595573
7,7.985000,239.550000,42.529412,3.269000,4.7,Martin City,145,2010,38.882761,-94.589858
8,6.493333,194.800000,33.642857,3.075714,4.7,Strange Days,21,2018,39.110027,-94.579975
9,7.874359,236.230769,44.812500,3.198611,4.6,Torn Label,145,2014,39.092553,-94.573076
10,5.666667,170.000000,NaN,3.108333,4.5,Casual Animal,24,2018,39.092430,-94.579894
11,5.989474,179.631579,39.611111,3.115556,4.6,Stockyards,40,2015,39.094318,-94.605282
12,5.670000,170.100000,24.538462,3.304103,4.8,Crane,296,2015,39.004638,-94.462348
13,6.100000,183.000000,44.750000,3.091111,4.6,Border Brewing,19,2014,39.091602,-94.577989
14,5.361538,160.846154,NaN,3.120000,4.9,BKS,14,2017,39.013333,-94.725976
15,0.000000,0.000000,0.000000,0.000000,4.3,Green Room,0,2012,39.054571,-94.592997
16,0.000000,0.000000,0.000000,0.000000,4.4,McCoy's,0,1997,39.053362,-94.591739
17,0.000000,0.000000,0.000000,0.000000,4.7,East Forty,0,2018,39.018500,-94.278200
18,0.000000,0.000000,0.000000,0.000000,4.8,Call Sign,0,2018,39.135419,-94.573751
19,0.000000,0.000000,0.000000,0.000000,4.7,Colony,0,2016,39.142119,-94.577046
20,0.000000,0.000000,0.000000,0.000000,4.4,Rock and Run,0,2013,39.246199,-94.419025
0,0.000000,0.000000,0.000000,0.000000,4.8,Fringe Beerworks,0,2016,38.912800,-94.376600
0,0.000000,0.000000,0.000000,0.000000,4.3,Smoke Brewing,0,2016,38.913100,-94.377800
0,0.000000,0.000000,0.000000,0.000000,4.8,New Axiom,0,2018,38.920700,-94.358800

In [7]:
beerData = beerData.reset_index(drop=True)
beerData.head(25)

,Average ABV,Average Calories,Average IBU,Average Score,Google Rating,Name,Total Ratings,Year Opened,lat,long
0,6.540741,196.222222,30.687500,2.968000,4.6,The Big Rip,74,2013,39.125946,-94.578436
1,7.925000,237.750000,36.950000,3.612000,4.8,Boulevard,16237,1989,39.082248,-94.596602
2,5.731250,171.937500,21.300000,3.082857,4.5,Brewery Emperial,26,2016,39.090638,-94.578785
3,6.146154,184.769231,38.181818,3.050833,4.1,Calibration,19,2016,39.141180,-94.578750
4,6.183333,185.500000,46.461538,3.218500,4.6,Cinder Block,143,2013,39.140252,-94.579157
5,7.003125,210.093750,44.769231,3.066667,4.6,Double Shift,37,2015,39.091599,-94.577906
6,6.077778,182.166667,25.250000,3.174000,4.7,KC Bier,121,2014,38.985109,-94.595573
7,7.985000,239.550000,42.529412,3.269000,4.7,Martin City,145,2010,38.882761,-94.589858
8,6.493333,194.800000,33.642857,3.075714,4.7,Strange Days,21,2018,39.110027,-94.579975
9,7.874359,236.230769,44.812500,3.198611,4.6,Torn Label,145,2014,39.092553,-94.573076
10,5.666667,170.000000,NaN,3.108333,4.5,Casual Animal,24,2018,39.092430,-94.579894
11,5.989474,179.631579,39.611111,3.115556,4.6,Stockyards,40,2015,39.094318,-94.605282
12,5.670000,170.100000,24.538462,3.304103,4.8,Crane,296,2015,39.004638,-94.462348
13,6.100000,183.000000,44.750000,3.091111,4.6,Border Brewing,19,2014,39.091602,-94.577989
14,5.361538,160.846154,NaN,3.120000,4.9,BKS,14,2017,39.013333,-94.725976
15,0.000000,0.000000,0.000000,0.000000,4.3,Green Room,0,2012,39.054571,-94.592997
16,0.000000,0.000000,0.000000,0.000000,4.4,McCoy's,0,1997,39.053362,-94.591739
17,0.000000,0.000000,0.000000,0.000000,4.7,East Forty,0,2018,39.018500,-94.278200
18,0.000000,0.000000,0.000000,0.000000,4.8,Call Sign,0,2018,39.135419,-94.573751
19,0.000000,0.000000,0.000000,0.000000,4.7,Colony,0,2016,39.142119,-94.577046
20,0.000000,0.000000,0.000000,0.000000,4.4,Rock and Run,0,2013,39.246199,-94.419025
21,0.000000,0.000000,0.000000,0.000000,4.8,Fringe Beerworks,0,2016,38.912800,-94.376600
22,0.000000,0.000000,0.000000,0.000000,4.3,Smoke Brewing,0,2016,38.913100,-94.377800
23,0.000000,0.000000,0.000000,0.000000,4.8,New Axiom,0,2018,38.920700,-94.358800

In [8]:
beerData.to_json("year2.js", orient='records')